# Generated by Django 2.1.2 on 2018-11-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_collage_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collage',
            table='collage',
        ),
    ]
