# Generated by Django 2.1.2 on 2018-11-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
